# jobber_fsm/core/agent/browser_nav_agent.py
from __future__ import annotations

from typing import Any, List, Tuple, Callable

from jobber_fsm.core.agent.base import BaseAgent
from jobber_fsm.core.models.models import BrowserNavInput, BrowserNavOutput
from jobber_fsm.core.prompts import LLM_PROMPTS
from jobber_fsm.utils.logger import logger

# ──────────────────────────────────────────────────────────────────────────────
# Skills / tools you already had
# ──────────────────────────────────────────────────────────────────────────────
from jobber_fsm.core.skills.open_url import openurl
from jobber_fsm.core.skills.enter_text_and_click import enter_text_and_click
from jobber_fsm.core.skills.get_dom_with_content_type import (
    get_dom_with_content_type,
)
from jobber_fsm.core.skills.click_using_selector import click as click_element
from jobber_fsm.core.skills.enter_text_using_selector import (
    bulk_enter_text,
    entertext,
)
from jobber_fsm.core.skills.get_url import geturl
from jobber_fsm.core.skills.press_key_combination import press_key_combination
from jobber_fsm.core.skills.pdf_text_extractor import extract_text_from_pdf
from jobber_fsm.core.skills.upload_file import upload_file


class BrowserNavAgent(BaseAgent):
    """
    Executes the low-level browser steps generated by the planner.

    `auto_mode=True`  – never stop to ask the human  
    `auto_mode=False` – may request clarification interactively
    """

    def __init__(self, planner, *, auto_mode: bool = False) -> None:
        self.planner = planner
        self.auto_mode = auto_mode

        super().__init__(
            name="executor",
            system_prompt=LLM_PROMPTS["BROWSER_AGENT_PROMPT"],
            input_format=BrowserNavInput,
            output_format=BrowserNavOutput,
            keep_message_history=auto_mode,
            tools=self._tool_specs(),  # ← same list you had before
        )

    # ------------------------------------------------------------------ #
    # public entry-point – called by PlannerAgent
    # ------------------------------------------------------------------ #
    async def process_query(self, task_text: str) -> BrowserNavOutput:
        logger.debug("BrowserNavAgent: executing task -> %s", task_text)

        llm_reply: BrowserNavOutput = await self.run(
            BrowserNavInput(instruction=task_text)
        )

        #
        # TODO – map llm_reply.content to real Playwright actions and
        #        perform them; for now we just log in dry-run style.
        #
        logger.info("[dry-run] would perform ⇒ %s", llm_reply.content)

        return llm_reply

    # ------------------------------------------------------------------ #
    # internal helpers
    # ------------------------------------------------------------------ #
    def _tool_specs(self) -> List[Tuple[Callable, str]]:
        """Return the list of (function, prompt-snippet) tuples for tools."""
        return [
            (openurl,                    LLM_PROMPTS["OPEN_URL_PROMPT"]),
            (enter_text_and_click,       LLM_PROMPTS["ENTER_TEXT_AND_CLICK_PROMPT"]),
            (get_dom_with_content_type,  LLM_PROMPTS["GET_DOM_WITH_CONTENT_TYPE_PROMPT"]),
            (click_element,              LLM_PROMPTS["CLICK_PROMPT"]),
            (geturl,                     LLM_PROMPTS["GET_URL_PROMPT"]),
            (bulk_enter_text,            LLM_PROMPTS["BULK_ENTER_TEXT_PROMPT"]),
            (entertext,                  LLM_PROMPTS["ENTER_TEXT_PROMPT"]),
            (press_key_combination,      LLM_PROMPTS["PRESS_KEY_COMBINATION_PROMPT"]),
            (extract_text_from_pdf,      LLM_PROMPTS["EXTRACT_TEXT_FROM_PDF_PROMPT"]),
            (upload_file,                LLM_PROMPTS["UPLOAD_FILE_PROMPT"]),
        ]
