from __future__ import annotations
import json

from typing import List, Tuple, Callable

from jobber_fsm.core.agent.base import BaseAgent
from jobber_fsm.core.models.models import BrowserNavInput, BrowserNavOutput
from jobber_fsm.core.prompts import LLM_PROMPTS
from jobber_fsm.utils.logger import logger

# ──────────────────────────────────────────────────────────────────────────────
# Skills / tools you already had
# ──────────────────────────────────────────────────────────────────────────────
from jobber_fsm.core.skills.open_url import openurl
from jobber_fsm.core.skills.enter_text_and_click import enter_text_and_click
from jobber_fsm.core.skills.get_dom_with_content_type import (
    get_dom_with_content_type,
)
from jobber_fsm.core.skills.click_using_selector import click as click_element
from jobber_fsm.core.skills.enter_text_using_selector import (
    bulk_enter_text,
    entertext,
)
from jobber_fsm.core.skills.get_url import geturl
from jobber_fsm.core.skills.press_key_combination import press_key_combination
from jobber_fsm.core.skills.pdf_text_extractor import extract_text_from_pdf
from jobber_fsm.core.skills.upload_file import upload_file
from jobber_fsm.core.skills.check_login_status import check_login_status

from jobber_fsm.core.memory.credentials import get_credentials, save_credentials, get_default_password

from jobber_fsm.core.models.models import Task
from itertools import count

_task_seq = count(1)   # simple auto-incrementing id per run

def _mk_task(bullet: str) -> Task:
    """
    Convert one markdown-bullet line into a minimal Task object.
    Only *description* is meaningful for the executor right now;
    other required fields are stubbed.
    """
    return Task(
        id       = next(_task_seq),
        description = bullet.lstrip("- ").strip(),
        url      = None,
        result   = "",
    )


class BrowserNavAgent(BaseAgent):
    """
    Executes the low-level browser steps generated by the planner.

    `auto_mode=True`  – never stop to ask the human  
    `auto_mode=False` – may request clarification interactively
    """

    def __init__(self, planner, *, auto_mode: bool = False) -> None:
        self.planner = planner
        self.auto_mode = auto_mode
        self.screenshot_debugger = None  # Will be set by cloud_job_runner

        super().__init__(
            name="executor",
            system_prompt=LLM_PROMPTS["BROWSER_AGENT_PROMPT"],
            input_format=BrowserNavInput,
            output_format=BrowserNavOutput,
            keep_message_history=auto_mode,
            tools=self._tool_specs(),
        )

    # ------------------------------------------------------------------ #
    # public entry-point – called by PlannerAgent
    # ------------------------------------------------------------------ #
    async def process_query(self, task_text: str) -> BrowserNavOutput:
        logger.info(f"[BrowserNavAgent] Starting task: {task_text}")
        logger.debug("BrowserNavAgent: executing task -> %s", task_text)

        # Helper function to take screenshots
        async def take_screenshot(name: str, description: str):
            logger.info(f"[BrowserNavAgent] Attempting screenshot: {name} - {description}")
            if self.screenshot_debugger:
                try:
                    from jobber_fsm.core.web_driver.playwright import PlaywrightManager
                    browser_manager = PlaywrightManager()
                    page = await browser_manager.get_current_page()
                    if page:
                        logger.info(f"[Screenshot] Taking screenshot: {name}")
                        logger.info(f"[Screenshot] Current URL: {page.url}")
                        path = await self.screenshot_debugger.capture(page, name, description)
                        if path:
                            logger.info(f"[Screenshot] Saved successfully: {path}")
                        else:
                            logger.warning(f"[Screenshot] Failed to save: {name}")
                    else:
                        logger.warning("[Screenshot] No page available")
                except Exception as e:
                    logger.error(f"[Screenshot] Error: {e}", exc_info=True)
            else:
                logger.warning("[BrowserNavAgent] No screenshot debugger available!")

        # Take pre-task screenshot
        await take_screenshot(f"task_start", f"Starting: {task_text}")

        llm_reply: BrowserNavOutput = await self.run(
            BrowserNavInput(task=_mk_task(task_text))
        )

        logger.info(f"[BrowserNavAgent] LLM decided to use tools: {getattr(llm_reply, 'tool_calls', None) is not None}")

        if getattr(llm_reply, "tool_calls", None):
            for i, call in enumerate(llm_reply.tool_calls):
                logger.info(f"[BrowserNavAgent] Executing tool {i+1}: {call.function.name}")
                # Take pre-tool screenshot
                await take_screenshot(f"before_{call.function.name}_{i}", f"Before {call.function.name}")
                
                msg = await self._apply_tool(call)
                logger.info(f"[BrowserNavAgent] Tool result: {call.function.name} → {msg}")
                
                # Take post-tool screenshot
                await take_screenshot(f"after_{call.function.name}_{i}", f"Result: {msg[:100]}")

        # Take post-task screenshot
        await take_screenshot(f"task_end", f"Completed: {task_text}")

        logger.info(f"[BrowserNavAgent] Task completed: {task_text}")
        return llm_reply
    
    async def check_for_security_page(page) -> bool:
        """Check if we're on a security/verification page"""
        try:
            url = page.url.lower()
            title = await page.title()
            
            # Common indicators of security pages
            security_indicators = [
                'security-check',
                'verify',
                'captcha',
                'challenge',
                'bot-check',
                'human-check',
                'access-denied'
            ]
            
            # Check URL and title
            for indicator in security_indicators:
                if indicator in url or indicator in title.lower():
                    return True
                    
            # Check page content
            try:
                content = await page.content()
                if any(phrase in content.lower() for phrase in [
                    'verify you are human',
                    'security check',
                    'captcha',
                    'cloudflare',
                    'checking your browser'
                ]):
                    return True
            except:
                pass
                
            return False
        except Exception as e:
            logger.error(f"Error checking for security page: {e}")
            return False
    
    async def _apply_tool(self, tool_call) -> str:
        """Given one `tool_call` from the LLM, invoke the matching skill."""
        fn_name = tool_call.function.name
        args    = json.loads(tool_call.function.arguments)
        func    = self.executable_functions_list[fn_name]
        return await func(**args)

    # ------------------------------------------------------------------ #
    # internal helpers
    # ------------------------------------------------------------------ #
    def _tool_specs(self) -> List[Tuple[Callable, str]]:
        """Return the list of (function, prompt-snippet) tuples for tools."""
        return [
            (openurl,                    LLM_PROMPTS["OPEN_URL_PROMPT"]),
            (enter_text_and_click,       LLM_PROMPTS["ENTER_TEXT_AND_CLICK_PROMPT"]),
            (get_dom_with_content_type,  LLM_PROMPTS["GET_DOM_WITH_CONTENT_TYPE_PROMPT"]),
            (click_element,              LLM_PROMPTS["CLICK_PROMPT"]),
            (geturl,                     LLM_PROMPTS["GET_URL_PROMPT"]),
            (bulk_enter_text,            LLM_PROMPTS["BULK_ENTER_TEXT_PROMPT"]),
            (entertext,                  LLM_PROMPTS["ENTER_TEXT_PROMPT"]),
            (press_key_combination,      LLM_PROMPTS["PRESS_KEY_COMBINATION_PROMPT"]),
            (extract_text_from_pdf,      LLM_PROMPTS["EXTRACT_TEXT_FROM_PDF_PROMPT"]),
            (upload_file,                LLM_PROMPTS["UPLOAD_FILE_PROMPT"]),
            (check_login_status,         "Check if the user is currently logged into the website by looking for login/logout indicators"),
        ]
